### ISSUE TITLE
Publishing content_type is always text/plain

### ISSUE THREAD

**Issue by andrefigueira** [olivertappin/scoop#1]
Hello,

There's been an issue in using scoop that has seemingly created an issue in queues that are using messages with content types other than text/plain

looking at the code, the content type is always fixed to text/plain meaning if used on a queue where messages are different to this, it can cause issues on the consuming application.

https://github.com/olivertappin/scoop/blob/master/scoop/scoop.go#L184

I would suggest we need to accept content_type as a parameter, rather than only being hardcoded, this gives the option to choose the content_type at point of use.

I can try open a PR, if this is ok?

**Comment by olivertappin** [comment]
Thanks for the contribution @andrefigueira 🎉 

Absolutely. This is a good feature request and I'm happy to get this in.

I'll review the code shortly and get back to you.

**Comment by olivertappin** [comment]
@andrefigueira after thinking about this in detail, I'm thinking we should remove it as an option, and simply read the existing message content type instead? Scoop was built as a dumb consumer, so modifying the message in any way is sort of outside the scope of what Scoop should be used for. What do you think?

**Comment by olivertappin** [comment]
This has been addressed in [2.1.0](https://github.com/olivertappin/scoop/releases/tag/2.1.0). More specifically, we are ensuring all the various parts of the message are passed on to the publisher. For more information, see [these lines](https://github.com/olivertappin/scoop/blob/2.1.0/scoop/scoop.go#L220-L233).
