### ISSUE TITLE
Use separate channels for Consume and Publish

### ISSUE THREAD

**Issue by danneaves-ee** [olivertappin/scoop#2]
https://github.com/olivertappin/scoop/blob/57f180720ea31cf21860aa751a428d2b7d597d1c/scoop/scoop.go#L178

In https://godoc.org/github.com/streadway/amqp#Channel.Consume it states;

```It's advisable to use separate connections for Channel.Publish and Channel.Consume so not to have TCP pushback on publishing affect the ability to consume messages, so this parameter is here mostly for completeness.```

It might be advisable to separate the channels for greater robustness.

**Comment by olivertappin** [comment]
Great call out here @danneaves-ee. We should definitely get this changed.

**Comment by olivertappin** [comment]
This has been addressed in the following pull-request: https://github.com/olivertappin/scoop/pull/5

@danneaves-ee would you like to review this and make sure it's in-line with your ask?

**Comment by olivertappin** [comment]
This has been addressed in [2.1.0](https://github.com/olivertappin/scoop/releases/tag/2.1.0).
